apiVersion: v1
kind: Service
metadata:
  name: go-demo-web
  labels:
    app: go-demo-web
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: go-demo-web
  type: ClusterIP
